export const ADD_ADVENTURE = "ADD_ADVENTURE";
export const REMOVE_ADVENTURE = "REMOVE_ADVENTURE";
export const GET_ADVENTURES = "GET_ADVENTURES";
export const SET_CAMPAIGNS = "SET_CAMPAIGNS";
export const SET_SESSIONS = "SET_SESSIONS";
export const SET_CAMPAIGN_CRESTS = "SET_CAMPAIGN_CRESTS";
