export const SET_SELECTED_CAMPAIGN = "SET_SELECTED_CAMPAIGN"
export const SET_SELECTED_PLAYER = "SET_SELECTED_PLAYER"
export const UPDATE_SELECTED_PLAYER = "UPDATE_SELECTED_PLAYER"
export const SET_SELECTED_SESSION = "SET_SELECTED_SESSION"

