export const SET_SELECTED_CAMPAIGN = "SET_SELECTED_CAMPAIGN";
export const SET_SELECTED_PLAYER = "SET_SELECTED_PLAYER";
export const SET_BACKGROUND_IMAGE = "SET_BACKGROUND_IMAGE";
export const UPDATE_SELECTED_PLAYER = "UPDATE_SELECTED_PLAYER";
export const SET_SELECTED_SESSION = "SET_SELECTED_SESSION";
export const SET_SELECTED_CAMPAIGN_BY_SLUG = "SET_SELECTED_CAMPAIGN_BY_SLUG"
