import React from "react";
import styled from "styled-components";
function CurseOfStrahd() {
    return (
        <Container>

            <h1>CurseOfStrahd</h1>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur euismod consequat mi, ac ultrices metus efficitur a. Nullam lacinia est vitae diam elementum fermentum. Nulla luctus dui in tellus condimentum auctor. Ut ut maximus dolor. Donec congue ligula mattis dolor dictum, nec commodo purus molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer placerat volutpat sagittis. Mauris mattis a urna ut rhoncus. Nunc sed neque maximus, porttitor neque nec, laoreet risus. Ut sodales lorem id euismod euismod. Nullam volutpat dignissim massa non ullamcorper. Nullam quis enim nec sem sollicitudin varius in id nulla. Nunc sit amet risus sit amet tortor efficitur varius.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur euismod consequat mi, ac ultrices metus efficitur a. Nullam lacinia est vitae diam elementum fermentum. Nulla luctus dui in tellus condimentum auctor. Ut ut maximus dolor. Donec congue ligula mattis dolor dictum, nec commodo purus molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer placerat volutpat sagittis. Mauris mattis a urna ut rhoncus. Nunc sed neque maximus, porttitor neque nec, laoreet risus. Ut sodales lorem id euismod euismod. Nullam volutpat dignissim massa non ullamcorper. Nullam quis enim nec sem sollicitudin varius in id nulla. Nunc sit amet risus sit amet tortor efficitur varius.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur euismod consequat mi, ac ultrices metus efficitur a. Nullam lacinia est vitae diam elementum fermentum. Nulla luctus dui in tellus condimentum auctor. Ut ut maximus dolor. Donec congue ligula mattis dolor dictum, nec commodo purus molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer placerat volutpat sagittis. Mauris mattis a urna ut rhoncus. Nunc sed neque maximus, porttitor neque nec, laoreet risus. Ut sodales lorem id euismod euismod. Nullam volutpat dignissim massa non ullamcorper. Nullam quis enim nec sem sollicitudin varius in id nulla. Nunc sit amet risus sit amet tortor efficitur varius.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur euismod consequat mi, ac ultrices metus efficitur a. Nullam lacinia est vitae diam elementum fermentum. Nulla luctus dui in tellus condimentum auctor. Ut ut maximus dolor. Donec congue ligula mattis dolor dictum, nec commodo purus molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer placerat volutpat sagittis. Mauris mattis a urna ut rhoncus. Nunc sed neque maximus, porttitor neque nec, laoreet risus. Ut sodales lorem id euismod euismod. Nullam volutpat dignissim massa non ullamcorper. Nullam quis enim nec sem sollicitudin varius in id nulla. Nunc sit amet risus sit amet tortor efficitur varius.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur euismod consequat mi, ac ultrices metus efficitur a. Nullam lacinia est vitae diam elementum fermentum. Nulla luctus dui in tellus condimentum auctor. Ut ut maximus dolor. Donec congue ligula mattis dolor dictum, nec commodo purus molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer placerat volutpat sagittis. Mauris mattis a urna ut rhoncus. Nunc sed neque maximus, porttitor neque nec, laoreet risus. Ut sodales lorem id euismod euismod. Nullam volutpat dignissim massa non ullamcorper. Nullam quis enim nec sem sollicitudin varius in id nulla. Nunc sit amet risus sit amet tortor efficitur varius.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur euismod consequat mi, ac ultrices metus efficitur a. Nullam lacinia est vitae diam elementum fermentum. Nulla luctus dui in tellus condimentum auctor. Ut ut maximus dolor. Donec congue ligula mattis dolor dictum, nec commodo purus molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer placerat volutpat sagittis. Mauris mattis a urna ut rhoncus. Nunc sed neque maximus, porttitor neque nec, laoreet risus. Ut sodales lorem id euismod euismod. Nullam volutpat dignissim massa non ullamcorper. Nullam quis enim nec sem sollicitudin varius in id nulla. Nunc sit amet risus sit amet tortor efficitur varius.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur euismod consequat mi, ac ultrices metus efficitur a. Nullam lacinia est vitae diam elementum fermentum. Nulla luctus dui in tellus condimentum auctor. Ut ut maximus dolor. Donec congue ligula mattis dolor dictum, nec commodo purus molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer placerat volutpat sagittis. Mauris mattis a urna ut rhoncus. Nunc sed neque maximus, porttitor neque nec, laoreet risus. Ut sodales lorem id euismod euismod. Nullam volutpat dignissim massa non ullamcorper. Nullam quis enim nec sem sollicitudin varius in id nulla. Nunc sit amet risus sit amet tortor efficitur varius.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur euismod consequat mi, ac ultrices metus efficitur a. Nullam lacinia est vitae diam elementum fermentum. Nulla luctus dui in tellus condimentum auctor. Ut ut maximus dolor. Donec congue ligula mattis dolor dictum, nec commodo purus molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer placerat volutpat sagittis. Mauris mattis a urna ut rhoncus. Nunc sed neque maximus, porttitor neque nec, laoreet risus. Ut sodales lorem id euismod euismod. Nullam volutpat dignissim massa non ullamcorper. Nullam quis enim nec sem sollicitudin varius in id nulla. Nunc sit amet risus sit amet tortor efficitur varius.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur euismod consequat mi, ac ultrices metus efficitur a. Nullam lacinia est vitae diam elementum fermentum. Nulla luctus dui in tellus condimentum auctor. Ut ut maximus dolor. Donec congue ligula mattis dolor dictum, nec commodo purus molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer placerat volutpat sagittis. Mauris mattis a urna ut rhoncus. Nunc sed neque maximus, porttitor neque nec, laoreet risus. Ut sodales lorem id euismod euismod. Nullam volutpat dignissim massa non ullamcorper. Nullam quis enim nec sem sollicitudin varius in id nulla. Nunc sit amet risus sit amet tortor efficitur varius.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur euismod consequat mi, ac ultrices metus efficitur a. Nullam lacinia est vitae diam elementum fermentum. Nulla luctus dui in tellus condimentum auctor. Ut ut maximus dolor. Donec congue ligula mattis dolor dictum, nec commodo purus molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer placerat volutpat sagittis. Mauris mattis a urna ut rhoncus. Nunc sed neque maximus, porttitor neque nec, laoreet risus. Ut sodales lorem id euismod euismod. Nullam volutpat dignissim massa non ullamcorper. Nullam quis enim nec sem sollicitudin varius in id nulla. Nunc sit amet risus sit amet tortor efficitur varius.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur euismod consequat mi, ac ultrices metus efficitur a. Nullam lacinia est vitae diam elementum fermentum. Nulla luctus dui in tellus condimentum auctor. Ut ut maximus dolor. Donec congue ligula mattis dolor dictum, nec commodo purus molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer placerat volutpat sagittis. Mauris mattis a urna ut rhoncus. Nunc sed neque maximus, porttitor neque nec, laoreet risus. Ut sodales lorem id euismod euismod. Nullam volutpat dignissim massa non ullamcorper. Nullam quis enim nec sem sollicitudin varius in id nulla. Nunc sit amet risus sit amet tortor efficitur varius.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur euismod consequat mi, ac ultrices metus efficitur a. Nullam lacinia est vitae diam elementum fermentum. Nulla luctus dui in tellus condimentum auctor. Ut ut maximus dolor. Donec congue ligula mattis dolor dictum, nec commodo purus molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer placerat volutpat sagittis. Mauris mattis a urna ut rhoncus. Nunc sed neque maximus, porttitor neque nec, laoreet risus. Ut sodales lorem id euismod euismod. Nullam volutpat dignissim massa non ullamcorper. Nullam quis enim nec sem sollicitudin varius in id nulla. Nunc sit amet risus sit amet tortor efficitur varius.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur euismod consequat mi, ac ultrices metus efficitur a. Nullam lacinia est vitae diam elementum fermentum. Nulla luctus dui in tellus condimentum auctor. Ut ut maximus dolor. Donec congue ligula mattis dolor dictum, nec commodo purus molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer placerat volutpat sagittis. Mauris mattis a urna ut rhoncus. Nunc sed neque maximus, porttitor neque nec, laoreet risus. Ut sodales lorem id euismod euismod. Nullam volutpat dignissim massa non ullamcorper. Nullam quis enim nec sem sollicitudin varius in id nulla. Nunc sit amet risus sit amet tortor efficitur varius.
            </p>
        </Container>
    )


}
const Container = styled.div`
    display:flex;
    justify-content:center;
    align-items: center;
    flex-direction: column;
    padding:5%;
    padding-top:5rem;
`
export default CurseOfStrahd